#!/bin/bash

set -e

OWNER="${1:-}"
REPO="${2:-}"
GITHUB_TOKEN="${3:-}"
PROJECT_NAME="${4:-}"

if [ -z "$OWNER" ] || [ -z "$REPO" ] || [ -z "$GITHUB_TOKEN" ]; then
    echo "Usage: $0 <owner> <repo> <github_token> [project_name]"
    echo "Example: $0 sera-inc my-project ghp_xxxxx 'My Project'"
    exit 1
fi

if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME="$REPO Project"
fi

echo "🚀 Setting up GitHub Project for $OWNER/$REPO..."
echo "📋 Project Name: $PROJECT_NAME"

API_URL="https://api.github.com"
GRAPHQL_URL="https://api.github.com/graphql"

AUTH_HEADER="Authorization: Bearer $GITHUB_TOKEN"

echo ""
echo "⚠️  Note: This script requires GitHub Projects v2 API access."
echo "⚠️  GitHub Projects v2 uses GraphQL API which requires organization-level permissions."
echo ""
echo "📝 Manual Setup Required:"
echo ""
echo "1. Go to: https://github.com/orgs/$OWNER/projects"
echo "2. Click 'New project'"
echo "3. Project name: $PROJECT_NAME"
echo "4. Template: 'Team backlog'"
echo "5. Click 'Create project'"
echo ""
echo "Then configure custom fields:"
echo ""
echo "=== Custom Fields ==="
echo ""
echo "1. Status (Single select) - Edit existing field:"
echo "   - 📋 Backlog (Gray)"
echo "   - 🔍 Ready (Blue)"
echo "   - 🚀 In Progress (Yellow)"
echo "   - 👀 Review (Orange)"
echo "   - ✅ Done (Green)"
echo "   - ❌ Blocked (Red)"
echo ""
echo "2. Priority (Single select):"
echo "   - 🔴 Critical (Red)"
echo "   - 🟠 High (Orange)"
echo "   - 🟡 Medium (Yellow)"
echo "   - 🔵 Low (Blue)"
echo ""
echo "3. Component (Single select):"
echo "   - 🎨 Frontend (Blue)"
echo "   - ⚙️ Backend (Purple)"
echo "   - 🗄️ Database (Orange)"
echo "   - 🏗️ Infrastructure (Gray)"
echo "   - 🎭 UI/UX (Pink)"
echo "   - 📱 API (Green)"
echo ""
echo "4. Sprint (Single select):"
echo "   - Sprint 1 (Blue)"
echo "   - Sprint 2 (Green)"
echo "   - Sprint 3 (Orange)"
echo "   - Sprint 4 (Purple)"
echo ""
echo "5. Story Points (Single select):"
echo "   - 1, 2, 3, 5, 8, 13, 21"
echo ""
echo "6. Must/Want (Single select):"
echo "   - 🚨 Must (Red)"
echo "   - 💫 Want (Blue)"
echo ""
echo "7. Figma Link (URL)"
echo ""
echo "8. Security Status (Single select):"
echo "   - ✅ Checked (Green)"
echo "   - 🔍 Checking (Yellow)"
echo "   - ❌ Not Checked (Red)"
echo "   - N/A (Gray)"
echo ""
echo "9. Review Status (Single select):"
echo "   - ✅ Approved (Green)"
echo "   - 🔍 In Review (Orange)"
echo "   - 📝 Changes Requested (Red)"
echo "   - ⏳ Pending (Yellow)"
echo ""
echo "=== Views ==="
echo ""
echo "1. 📊 Main Kanban (Board)"
echo "   - Group by: Status"
echo "   - Filter: is:open"
echo "   - Sort: Priority (desc), Story Points (asc)"
echo ""
echo "2. 🏃 Sprint Board (Board)"
echo "   - Group by: Status"
echo "   - Filter: is:open, Sprint equals 'Sprint 1'"
echo "   - Sort: Priority (desc)"
echo ""
echo "3. 👥 Team Members (Board)"
echo "   - Group by: Assignees"
echo "   - Filter: is:open"
echo "   - Sort: Priority (desc)"
echo ""
echo "4. 🔥 Priority View (Table)"
echo "   - Filter: is:open"
echo "   - Sort: Priority (desc), Story Points (desc)"
echo ""
echo "5. 🔧 Component View (Board)"
echo "   - Group by: Component"
echo "   - Filter: is:open"
echo "   - Sort: Priority (desc)"
echo ""
echo "6. 👀 Review Pipeline (Board)"
echo "   - Group by: Review Status"
echo "   - Filter: is:open, Status not equal 'Backlog'"
echo "   - Sort: Priority (desc)"
echo ""
echo "7. ✅ Completed Tasks (Table)"
echo "   - Filter: is:closed, closed date within last 30 days"
echo "   - Sort: Closed date (desc)"
echo ""
echo "=== Automation Rules ==="
echo ""
echo "1. Auto-add Issues:"
echo "   - Trigger: Issue created"
echo "   - Action: Add to project"
echo "   - Default: Status=Backlog, Priority=Medium"
echo ""
echo "2. Auto-add Pull Requests:"
echo "   - Trigger: Pull request created"
echo "   - Action: Add to project"
echo "   - Default: Status=Review, Priority=Medium"
echo ""
echo "3. Auto-update on merge:"
echo "   - Trigger: Pull request merged"
echo "   - Action: Set Status to 'Done'"
echo ""
echo "=== Permissions ==="
echo ""
echo "Add team members with appropriate roles:"
echo "  - Project Manager: Admin"
echo "  - Lead Developer: Write"
echo "  - Developers: Write"
echo "  - Designer: Write"
echo "  - QA Engineer: Write"
echo "  - Client: Read"
echo ""
echo "✅ Setup instructions displayed."
echo ""
echo "📚 For detailed setup guide, see:"
echo "   https://github.com/$OWNER/.github/blob/main/github-projects-setup.md"
echo ""
echo "💡 Tip: After creating the project, link it to your repository:"
echo "   Repository Settings → Features → Projects → Link a project"
